-- Restaurant POS database schema for Supabase/PostgreSQL.
-- Run this script in Supabase SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price > 0),
  icon text not null default '🍽️',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menu_items_active_category_idx
  on public.menu_items (is_active, category);


-- Menu change history: one append-only row for every INSERT, UPDATE, or DELETE.
-- Each row stores the menu item snapshot at the time of the change.
create table if not exists public.menu_item_history (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  name text,
  category text,
  price numeric(12,2),
  icon text,
  created_at timestamptz not null default now()
);

create index if not exists menu_item_history_item_idx
  on public.menu_item_history (menu_item_id, created_at desc);

-- Upgrade an older version of menu_item_history if it was already created.
do $
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_item_history'
      and column_name = 'action'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_item_history'
      and column_name = 'operation'
  ) then
    alter table public.menu_item_history rename column action to operation;
  end if;
end $;

alter table public.menu_item_history
  add column if not exists name text,
  add column if not exists category text,
  add column if not exists price numeric(12,2),
  add column if not exists icon text;

alter table public.menu_item_history
  drop column if exists old_price,
  drop column if exists new_price,
  drop column if exists old_is_active,
  drop column if exists new_is_active;


alter table public.menu_item_history enable row level security;

drop policy if exists "menu_item_history_public_read" on public.menu_item_history;
create policy "menu_item_history_public_read"
  on public.menu_item_history for select
  to anon, authenticated
  using (true);

create or replace function public.audit_menu_item_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      new.id, 'INSERT', new.name, new.category, new.price, new.icon
    );
    return new;

  elsif tg_op = 'UPDATE' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      new.id, 'UPDATE', new.name, new.category, new.price, new.icon
    );
    return new;

  elsif tg_op = 'DELETE' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      old.id, 'DELETE', old.name, old.category, old.price, old.icon
    );
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists menu_items_audit_history on public.menu_items;
create trigger menu_items_audit_history
after insert or update or delete on public.menu_items
for each row execute function public.audit_menu_item_history();

create index if not exists menu_items_active_category_idx
  on public.menu_items (is_active, category);


-- Menu change history keeps a lightweight audit trail for every create/update/delete.
-- Invoice items keep the transaction-time price separately, so old invoices never
-- change when the menu price changes later.
create table if not exists public.menu_item_history (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  old_price numeric(12,2),
  new_price numeric(12,2),
  old_is_active boolean,
  new_is_active boolean,
  created_at timestamptz not null default now()
);

create index if not exists menu_item_history_item_idx
  on public.menu_item_history (menu_item_id, created_at desc);

alter table public.menu_item_history enable row level security;

drop policy if exists "menu_item_history_public_read" on public.menu_item_history;
create policy "menu_item_history_public_read"
  on public.menu_item_history for select
  to anon, authenticated
  using (true);

create or replace function public.audit_menu_item_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $
begin
  if tg_op = 'INSERT' then
    insert into public.menu_item_history (
      menu_item_id, action, old_price, new_price,
      old_is_active, new_is_active
    )
    values (
      new.id, 'INSERT', null, new.price,
      null, new.is_active
    );
    return new;

  elsif tg_op = 'UPDATE' then
    insert into public.menu_item_history (
      menu_item_id, action, old_price, new_price,
      old_is_active, new_is_active
    )
    values (
      new.id,
      case
        when old.is_active = true and new.is_active = false then 'DELETE'
        else 'UPDATE'
      end,
      old.price,
      new.price,
      old.is_active,
      new.is_active
    );
    return new;

  elsif tg_op = 'DELETE' then
    insert into public.menu_item_history (
      menu_item_id, action, old_price, new_price,
      old_is_active, new_is_active
    )
    values (
      old.id, 'DELETE', old.price, null,
      old.is_active, null
    );
    return old;
  end if;

  return null;
end;
$;

drop trigger if exists menu_items_audit_history on public.menu_items;
create trigger menu_items_audit_history
after insert or update or delete on public.menu_items
for each row execute function public.audit_menu_item_history();


create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

alter table public.menu_items enable row level security;

-- MVP policy: the static frontend currently has no authentication.
-- These policies allow the app to manage menu items with the publishable key.
-- Before production/multi-restaurant use, replace these with authenticated
-- policies scoped by restaurant/user and remove the anonymous write policies.
drop policy if exists "menu_items_public_read" on public.menu_items;
drop policy if exists "menu_items_public_insert" on public.menu_items;
drop policy if exists "menu_items_public_update" on public.menu_items;
drop policy if exists "menu_items_public_delete" on public.menu_items;

create policy "menu_items_public_read"
  on public.menu_items for select
  to anon, authenticated
  using (true);

create policy "menu_items_public_insert"
  on public.menu_items for insert
  to anon, authenticated
  with check (true);

create policy "menu_items_public_update"
  on public.menu_items for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "menu_items_public_delete"
  on public.menu_items for delete
  to anon, authenticated
  using (true);

-- Seed the current default menu only when the table is empty.
insert into public.menu_items (name, category, price, icon)
select v.name, v.category, v.price, v.icon
from (values
  ('Chicken Biriyani', 'Main Course', 180.00, '🍗'),
  ('Mutton Biriyani', 'Main Course', 240.00, '🍖'),
  ('Fish Curry', 'Main Course', 150.00, '🐟'),
  ('Chicken 65', 'Starters', 140.00, '🍗'),
  ('Paneer 65', 'Starters', 130.00, '🧀'),
  ('Veg Meals', 'Meals', 120.00, '🍛'),
  ('Parotta', 'Breads', 25.00, '🥞'),
  ('Chapati', 'Breads', 30.00, '🫓'),
  ('Curd Rice', 'Meals', 80.00, '🍚'),
  ('Fresh Lime', 'Drinks', 50.00, '🍋'),
  ('Coke', 'Drinks', 40.00, '🥤'),
  ('Water Bottle', 'Drinks', 20.00, '💧')
) as v(name, category, price, icon)
where not exists (select 1 from public.menu_items);


-- Invoice header: one row per generated bill.
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  customer_name text not null default 'Walk-in Customer',
  invoice_date timestamptz not null default now(),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  tax numeric(12,2) not null check (tax >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoices_invoice_date_idx
  on public.invoices (invoice_date desc);

-- Invoice lines keep a snapshot of the item name and price at billing time.
create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoice_items_invoice_id_idx
  on public.invoice_items (invoice_id);

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

drop policy if exists "invoices_public_read" on public.invoices;
drop policy if exists "invoices_public_insert" on public.invoices;
drop policy if exists "invoices_public_update" on public.invoices;
drop policy if exists "invoices_public_delete" on public.invoices;

create policy "invoices_public_read"
  on public.invoices for select
  to anon, authenticated
  using (true);

create policy "invoices_public_insert"
  on public.invoices for insert
  to anon, authenticated
  with check (true);

create policy "invoices_public_update"
  on public.invoices for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "invoices_public_delete"
  on public.invoices for delete
  to anon, authenticated
  using (true);

drop policy if exists "invoice_items_public_read" on public.invoice_items;
drop policy if exists "invoice_items_public_insert" on public.invoice_items;
drop policy if exists "invoice_items_public_update" on public.invoice_items;
drop policy if exists "invoice_items_public_delete" on public.invoice_items;

create policy "invoice_items_public_read"
  on public.invoice_items for select
  to anon, authenticated
  using (true);

create policy "invoice_items_public_insert"
  on public.invoice_items for insert
  to anon, authenticated
  with check (true);

create policy "invoice_items_public_update"
  on public.invoice_items for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "invoice_items_public_delete"
  on public.invoice_items for delete
  to anon, authenticated
  using (true);
