-- Restaurant POS database schema for Supabase/PostgreSQL.
-- Run this script in Supabase SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price > 0),
  icon text not null default '🍽️',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menu_items_active_category_idx
  on public.menu_items (is_active, category);


-- Menu change history: one snapshot for every INSERT, UPDATE, or DELETE.
create table if not exists public.menu_item_history (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  name text,
  category text,
  price numeric(12,2),
  icon text,
  created_at timestamptz not null default now()
);

create index if not exists menu_item_history_item_idx
  on public.menu_item_history (menu_item_id, created_at desc);

alter table public.menu_item_history enable row level security;

drop policy if exists "menu_item_history_public_read" on public.menu_item_history;
create policy "menu_item_history_public_read"
  on public.menu_item_history for select
  to anon, authenticated
  using (true);

create or replace function public.audit_menu_item_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      new.id, 'INSERT', new.name, new.category, new.price, new.icon
    );
    return new;

  elsif tg_op = 'UPDATE' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      new.id, 'UPDATE', new.name, new.category, new.price, new.icon
    );
    return new;

  elsif tg_op = 'DELETE' then
    insert into public.menu_item_history (
      menu_item_id, operation, name, category, price, icon
    )
    values (
      old.id, 'DELETE', old.name, old.category, old.price, old.icon
    );
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists menu_items_audit_history on public.menu_items;
create trigger menu_items_audit_history
after insert or update or delete on public.menu_items
for each row execute function public.audit_menu_item_history();

-- Invoice header: one row per generated bill.
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  customer_name text not null default 'Walk-in Customer',
  invoice_date timestamptz not null default now(),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  tax numeric(12,2) not null check (tax >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoices_invoice_date_idx
  on public.invoices (invoice_date desc);

-- Invoice lines keep a snapshot of the item name and price at billing time.
create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoice_items_invoice_id_idx
  on public.invoice_items (invoice_id);

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

drop policy if exists "invoices_public_read" on public.invoices;
drop policy if exists "invoices_public_insert" on public.invoices;
drop policy if exists "invoices_public_update" on public.invoices;
drop policy if exists "invoices_public_delete" on public.invoices;

create policy "invoices_public_read"
  on public.invoices for select
  to anon, authenticated
  using (true);

create policy "invoices_public_insert"
  on public.invoices for insert
  to anon, authenticated
  with check (true);

create policy "invoices_public_update"
  on public.invoices for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "invoices_public_delete"
  on public.invoices for delete
  to anon, authenticated
  using (true);

drop policy if exists "invoice_items_public_read" on public.invoice_items;
drop policy if exists "invoice_items_public_insert" on public.invoice_items;
drop policy if exists "invoice_items_public_update" on public.invoice_items;
drop policy if exists "invoice_items_public_delete" on public.invoice_items;

create policy "invoice_items_public_read"
  on public.invoice_items for select
  to anon, authenticated
  using (true);

create policy "invoice_items_public_insert"
  on public.invoice_items for insert
  to anon, authenticated
  with check (true);

create policy "invoice_items_public_update"
  on public.invoice_items for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "invoice_items_public_delete"
  on public.invoice_items for delete
  to anon, authenticated
  using (true);
