-- Restaurant POS database schema for Supabase/PostgreSQL.
-- Run this script in Supabase SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price > 0),
  icon text not null default '🍽️',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menu_items_active_category_idx
  on public.menu_items (is_active, category);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

alter table public.menu_items enable row level security;

-- MVP policy: the static frontend currently has no authentication.
-- These policies allow the app to manage menu items with the publishable key.
-- Before production/multi-restaurant use, replace these with authenticated
-- policies scoped by restaurant/user and remove the anonymous write policies.
drop policy if exists "menu_items_public_read" on public.menu_items;
drop policy if exists "menu_items_public_insert" on public.menu_items;
drop policy if exists "menu_items_public_update" on public.menu_items;
drop policy if exists "menu_items_public_delete" on public.menu_items;

create policy "menu_items_public_read"
  on public.menu_items for select
  to anon, authenticated
  using (true);

create policy "menu_items_public_insert"
  on public.menu_items for insert
  to anon, authenticated
  with check (true);

create policy "menu_items_public_update"
  on public.menu_items for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "menu_items_public_delete"
  on public.menu_items for delete
  to anon, authenticated
  using (true);

-- Seed the current default menu only when the table is empty.
insert into public.menu_items (name, category, price, icon)
select v.name, v.category, v.price, v.icon
from (values
  ('Chicken Biriyani', 'Main Course', 180.00, '🍗'),
  ('Mutton Biriyani', 'Main Course', 240.00, '🍖'),
  ('Fish Curry', 'Main Course', 150.00, '🐟'),
  ('Chicken 65', 'Starters', 140.00, '🍗'),
  ('Paneer 65', 'Starters', 130.00, '🧀'),
  ('Veg Meals', 'Meals', 120.00, '🍛'),
  ('Parotta', 'Breads', 25.00, '🥞'),
  ('Chapati', 'Breads', 30.00, '🫓'),
  ('Curd Rice', 'Meals', 80.00, '🍚'),
  ('Fresh Lime', 'Drinks', 50.00, '🍋'),
  ('Coke', 'Drinks', 40.00, '🥤'),
  ('Water Bottle', 'Drinks', 20.00, '💧')
) as v(name, category, price, icon)
where not exists (select 1 from public.menu_items);
