const supabaseConfig=window.SUPABASE_CONFIG||{};
const supabaseClient=window.supabase&&supabaseConfig.url&&supabaseConfig.publishableKey?window.supabase.createClient(supabaseConfig.url,supabaseConfig.publishableKey):null;
let selectedPeriod="today";
let refreshTimer=null;
const $=id=>document.getElementById(id);
const money=value=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(value||0);
const esc=value=>String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function rangeForPeriod(period){const now=new Date();const end=new Date(now);end.setHours(23,59,59,999);const start=new Date(now);if(period==="today")start.setHours(0,0,0,0);else{start.setDate(start.getDate()-Number(period)+1);start.setHours(0,0,0,0)}return{start,end}}
function previousRange(period){const current=rangeForPeriod(period);const days=period==="today"?1:Number(period);const end=new Date(current.start);end.setMilliseconds(-1);const start=new Date(end);start.setDate(start.getDate()-days+1);start.setHours(0,0,0,0);return{start,end}}
async function loadData(){if(!supabaseClient){renderEmpty("Connect Supabase to view live business analytics.");return}const current=rangeForPeriod(selectedPeriod);const previous=previousRange(selectedPeriod);const results=await Promise.all([supabaseClient.from("invoices").select("id,invoice_date,total").gte("invoice_date",current.start.toISOString()).lte("invoice_date",current.end.toISOString()).order("invoice_date"),supabaseClient.from("invoice_items").select("invoice_id,item_name,quantity,unit_price,line_total,menu_item_id,menu_items(category)").gte("created_at",current.start.toISOString()).lte("created_at",current.end.toISOString()),supabaseClient.from("invoices").select("id,total").gte("invoice_date",previous.start.toISOString()).lte("invoice_date",previous.end.toISOString())]);const invoiceResult=results[0],itemResult=results[1],prevInvoiceResult=results[2];if(invoiceResult.error||itemResult.error||prevInvoiceResult.error){console.error(invoiceResult.error||itemResult.error||prevInvoiceResult.error);renderEmpty("Unable to load dashboard data. Check your Supabase policies and connection.");return}renderDashboard(invoiceResult.data||[],itemResult.data||[],prevInvoiceResult.data||[])}
function renderDashboard(invoices,items,previousInvoices){const revenue=invoices.reduce((s,x)=>s+Number(x.total||0),0);const previousRevenue=previousInvoices.reduce((s,x)=>s+Number(x.total||0),0);const orders=invoices.length;const previousOrders=previousInvoices.length;const quantity=items.reduce((s,x)=>s+Number(x.quantity||0),0);const avg=orders?revenue/orders:0;$("revenue").textContent=money(revenue);$("orders").textContent=orders.toLocaleString("en-IN");$("itemsSold").textContent=quantity.toLocaleString("en-IN");$("avgBill").textContent=money(avg);setChange("revenueChange",revenue,previousRevenue,"revenue");setChange("ordersChange",orders,previousOrders,"orders");renderSalesChart(invoices);renderCategories(items);renderItems(items,revenue);$("dashboardNote").textContent=selectedPeriod==="today"?"Today's item revenue is calculated from saved invoice lines.":"Item revenue is calculated from invoice lines created during the selected period."}
function setChange(id,current,previous,label){const el=$(id);if(!previous){el.textContent=current?"No previous-period baseline":"No sales yet";el.className="metric-change";return}const pct=((current-previous)/previous)*100;el.textContent=(pct>=0?"↑ ":"↓ ")+Math.abs(pct).toFixed(1)+"% vs previous "+label;el.className="metric-change "+(pct<0?"down":"")}
function renderSalesChart(invoices){const chart=$("salesChart");const buckets=selectedPeriod==="today"?Array.from({length:12},(_,i)=>({label:(i*2===0?12:i*2)+(i<6?" AM":" PM"),value:0})):[];if(selectedPeriod==="today"){invoices.forEach(invoice=>{const hour=new Date(invoice.invoice_date).getHours();buckets[Math.floor(hour/2)].value+=Number(invoice.total||0)});$("salesChartTitle").textContent="Sales by hour"}else{$("salesChartTitle").textContent="Sales by day — last "+selectedPeriod+" days";const days=Number(selectedPeriod);for(let i=0;i<days;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-days+1+i);buckets.push({label:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short"}),value:0,date:d.toDateString()})}invoices.forEach(invoice=>{const d=new Date(invoice.invoice_date).toDateString();const bucket=buckets.find(x=>x.date===d);if(bucket)bucket.value+=Number(invoice.total||0)})}const max=Math.max(...buckets.map(x=>x.value),1);chart.innerHTML=buckets.map(b=>"<div class=\"bar-group\"><span class=\"bar-value\">"+(b.value?money(b.value):"")+"</span><div class=\"bar\" title=\""+esc(b.label)+": "+money(b.value)+"\" style=\"height:"+Math.max(b.value/max*82,b.value?3:0)+"%\"></div><span class=\"bar-label\">"+esc(b.label)+"</span></div>").join("")}
function renderCategories(items){const totals={};items.forEach(item=>{const key=item.menu_items?.category||"Other";totals[key]=(totals[key]||0)+Number(item.line_total||0)});const entries=Object.entries(totals).sort((a,b)=>b[1]-a[1]);const total=entries.reduce((s,x)=>s+x[1],0);const palette=["#ff7048","#5f8fe8","#63b98a","#c08be8","#e2b94d","#70b9c9"];let cursor=0;const stops=entries.map((x,i)=>{const pct=total?x[1]/total*100:0;const stop=palette[i%palette.length]+" "+cursor+"% "+(cursor+pct)+"%";cursor+=pct;return stop}).join(",");$("donut").style.background=entries.length?"conic-gradient("+stops+")":"conic-gradient(#e8e3dc 0 100%)";$("categoryLegend").innerHTML=entries.length?entries.map((x,i)=>"<div class=\"legend-row\"><span class=\"legend-dot\" style=\"background:"+palette[i%palette.length]+"\"></span><span>"+esc(x[0])+"</span><b>"+(total?(x[1]/total*100).toFixed(0):0)+"%</b></div>").join(""):"<span>No item sales yet.</span>"}
function renderItems(items,total){const map=new Map();items.forEach(item=>{const key=item.menu_item_id??item.item_name;const existing=map.get(key)||{name:item.item_name,category:item.menu_items?.category||"—",quantity:0,revenue:0};existing.quantity+=Number(item.quantity||0);existing.revenue+=Number(item.line_total||0);map.set(key,existing)});const rows=[...map.values()].sort((a,b)=>b.revenue-a.revenue);$("itemTableBody").innerHTML=rows.length?rows.map((item,i)=>{const share=total?item.revenue/total*100:0;return"<tr><td class=\"rank\">"+(i+1)+"</td><td><strong>"+esc(item.name)+"</strong></td><td>"+esc(item.category)+"</td><td>"+item.quantity.toLocaleString("en-IN")+"</td><td><strong>"+money(item.revenue)+"</strong></td><td><div class=\"progress\" title=\""+share.toFixed(1)+"%\"><span style=\"width:"+Math.min(100,share)+"%\"></span></div><small>"+share.toFixed(1)+"%</small></td></tr>"}).join(""):"<tr><td colspan=\"6\" class=\"empty-dashboard\">No sales found for this period.</td></tr>"}
function renderEmpty(message){$("revenue").textContent="₹0.00";$("orders").textContent="0";$("itemsSold").textContent="0";$("avgBill").textContent="₹0.00";$("itemTableBody").innerHTML="<tr><td colspan=\"6\" class=\"empty-dashboard\">"+esc(message)+"</td></tr>"}
$("periodSelect").addEventListener("change",e=>{selectedPeriod=e.target.value;loadData()});loadData();
if(supabaseClient){refreshTimer=setInterval(loadData,60000);supabaseClient.channel("dashboard-invoices").on("postgres_changes",{event:"*",schema:"public",table:"invoices"},loadData).on("postgres_changes",{event:"*",schema:"public",table:"invoice_items"},loadData).subscribe()}
window.addEventListener("beforeunload",()=>{if(refreshTimer)clearInterval(refreshTimer)});